codecov:
  token: 9cba8431-963c-4399-b7b3-9e9be764d8cd
  
comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
